# backend/pyproject.toml

[tool.djlint]
profile="jinja"
blank_line_after_tag="load,extends,include"
blank_line_before_tag="load,extends,include"
format_attribute_template_tags=true
line_break_after_multiline_tag=true
max_blank_lines=1
max_line_length=80
